### ISSUE TITLE
Way to stop Sidebar expanding

### ISSUE THREAD

**Issue by kikiyashi** [LostPaul/obsidian-folder-notes#130] opened 2024-07-09 05:20 UTC
As per normal Obsidian interface, when you select the folder in the title bar that has the path, it expands the lefthand side bar and highlights the location of the folder. Whilst having this plugin makes it so that i click the folder it allows me to go there via the path titlebar (which is perfect!), is there anyway to stop the left hand side bar still expanding upon clicking and the folder note? I often will have multiple panes open and be quickly navigating back and forth, and it just inconvenient - I know this is a function of vanilla obsidian, as I made a new vault to test it out.

**Comment by LostPaul** [comment] 2024-08-14 13:37
Dupe of #108 and it will be available soon.

**Closed by LostPaul** 2024-08-14 13:37 UTC
